// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAuBhLMSt-TDap-oLlWcgbKbUDvBv1O3E',
    appId: '1:96467453228:android:f9e39320e2bef3e2591889',
    messagingSenderId: '96467453228',
    projectId: 'bible-reflection',
    databaseURL: 'https://bible-reflection-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bible-reflection.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGNe8YzzohF_jCDeSwbyITNYkpIITrw-M',
    appId: '1:96467453228:web:70cdf51cda13cfc7591889',
    messagingSenderId: '96467453228',
    projectId: 'bible-reflection',
    authDomain: 'bible-reflection.firebaseapp.com',
    databaseURL: 'https://bible-reflection-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bible-reflection.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdtWn1hqyWi4XsRCEhv-XfumBTE3m-wmk',
    appId: '1:96467453228:ios:a03bd0e9bc838266591889',
    messagingSenderId: '96467453228',
    projectId: 'bible-reflection',
    databaseURL: 'https://bible-reflection-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bible-reflection.firebasestorage.app',
    iosBundleId: 'app.qt.reflection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGNe8YzzohF_jCDeSwbyITNYkpIITrw-M',
    appId: '1:96467453228:web:cc648aaf12b19b96591889',
    messagingSenderId: '96467453228',
    projectId: 'bible-reflection',
    authDomain: 'bible-reflection.firebaseapp.com',
    databaseURL: 'https://bible-reflection-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bible-reflection.firebasestorage.app',
  );
}
